language: python
python:
    - 2.7

branches:
  only:
    - master

virtualenv:
  system_site_packages: true

before_install:
    - sudo apt-get update
    - sudo apt-get install -qq python-numpy python-scipy ffmpeg

install:
    - pip install -r requirements.txt
    - pip install coveralls

script:
    nosetests --with-coverage

after_success:
    coveralls
